/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationApiApplicationV2ApplicationUpdatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationApiApplicationV2ApplicationUpdatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationApiApplicationV2ApplicationUpdatedResponse
        //private ApplicationApiApplicationV2ApplicationUpdatedResponse instance;

        public ApplicationApiApplicationV2ApplicationUpdatedResponseTests()
        {
            // TODO uncomment below to create an instance of ApplicationApiApplicationV2ApplicationUpdatedResponse
            //instance = new ApplicationApiApplicationV2ApplicationUpdatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationApiApplicationV2ApplicationUpdatedResponse
        /// </summary>
        [Fact]
        public void ApplicationApiApplicationV2ApplicationUpdatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationApiApplicationV2ApplicationUpdatedResponse
            //Assert.IsType<ApplicationApiApplicationV2ApplicationUpdatedResponse>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

    }

}
