/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobTypeV1ProfileCreatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobTypeV1ProfileCreatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobTypeV1ProfileCreatedResponse
        //private DataSyncApiJobTypeV1ProfileCreatedResponse instance;

        public DataSyncApiJobTypeV1ProfileCreatedResponseTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobTypeV1ProfileCreatedResponse
            //instance = new DataSyncApiJobTypeV1ProfileCreatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobTypeV1ProfileCreatedResponse
        /// </summary>
        [Fact]
        public void DataSyncApiJobTypeV1ProfileCreatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobTypeV1ProfileCreatedResponse
            //Assert.IsType<DataSyncApiJobTypeV1ProfileCreatedResponse>(instance);
        }


        /// <summary>
        /// Test the property 'JobTypeId'
        /// </summary>
        [Fact]
        public void JobTypeIdTest()
        {
            // TODO unit test for the property 'JobTypeId'
        }
        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Fact]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }

    }

}
