/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiProviderV1ConnectionMetadataField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiProviderV1ConnectionMetadataFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiProviderV1ConnectionMetadataField
        //private DataSyncApiProviderV1ConnectionMetadataField instance;

        public DataSyncApiProviderV1ConnectionMetadataFieldTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiProviderV1ConnectionMetadataField
            //instance = new DataSyncApiProviderV1ConnectionMetadataField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiProviderV1ConnectionMetadataField
        /// </summary>
        [Fact]
        public void DataSyncApiProviderV1ConnectionMetadataFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiProviderV1ConnectionMetadataField
            //Assert.IsType<DataSyncApiProviderV1ConnectionMetadataField>(instance);
        }


        /// <summary>
        /// Test the property 'Tab'
        /// </summary>
        [Fact]
        public void TabTest()
        {
            // TODO unit test for the property 'Tab'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Validation'
        /// </summary>
        [Fact]
        public void ValidationTest()
        {
            // TODO unit test for the property 'Validation'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Fact]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }
        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Fact]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Fact]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }
        /// <summary>
        /// Test the property 'IsSecret'
        /// </summary>
        [Fact]
        public void IsSecretTest()
        {
            // TODO unit test for the property 'IsSecret'
        }

    }

}
