/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiProviderV1UpdateProviderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiProviderV1UpdateProviderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiProviderV1UpdateProviderRequest
        //private DataSyncApiProviderV1UpdateProviderRequest instance;

        public DataSyncApiProviderV1UpdateProviderRequestTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiProviderV1UpdateProviderRequest
            //instance = new DataSyncApiProviderV1UpdateProviderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiProviderV1UpdateProviderRequest
        /// </summary>
        [Fact]
        public void DataSyncApiProviderV1UpdateProviderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiProviderV1UpdateProviderRequest
            //Assert.IsType<DataSyncApiProviderV1UpdateProviderRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IconUri'
        /// </summary>
        [Fact]
        public void IconUriTest()
        {
            // TODO unit test for the property 'IconUri'
        }

    }

}
