/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobTypeV1CreateProfileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobTypeV1CreateProfileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobTypeV1CreateProfileRequest
        //private DataSyncApiJobTypeV1CreateProfileRequest instance;

        public DataSyncApiJobTypeV1CreateProfileRequestTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobTypeV1CreateProfileRequest
            //instance = new DataSyncApiJobTypeV1CreateProfileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobTypeV1CreateProfileRequest
        /// </summary>
        [Fact]
        public void DataSyncApiJobTypeV1CreateProfileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobTypeV1CreateProfileRequest
            //Assert.IsType<DataSyncApiJobTypeV1CreateProfileRequest>(instance);
        }


        /// <summary>
        /// Test the property 'JobTypeId'
        /// </summary>
        [Fact]
        public void JobTypeIdTest()
        {
            // TODO unit test for the property 'JobTypeId'
        }
        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Fact]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ActorType'
        /// </summary>
        [Fact]
        public void ActorTypeTest()
        {
            // TODO unit test for the property 'ActorType'
        }

    }

}
