/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiProviderV1ProviderProfileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiProviderV1ProviderProfileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiProviderV1ProviderProfileResponse
        //private DataSyncApiProviderV1ProviderProfileResponse instance;

        public DataSyncApiProviderV1ProviderProfileResponseTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiProviderV1ProviderProfileResponse
            //instance = new DataSyncApiProviderV1ProviderProfileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiProviderV1ProviderProfileResponse
        /// </summary>
        [Fact]
        public void DataSyncApiProviderV1ProviderProfileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiProviderV1ProviderProfileResponse
            //Assert.IsType<DataSyncApiProviderV1ProviderProfileResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IconUri'
        /// </summary>
        [Fact]
        public void IconUriTest()
        {
            // TODO unit test for the property 'IconUri'
        }
        /// <summary>
        /// Test the property 'ConnectionTypes'
        /// </summary>
        [Fact]
        public void ConnectionTypesTest()
        {
            // TODO unit test for the property 'ConnectionTypes'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }
        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }

    }

}
