/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRoleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole
        //private EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole instance;

        public EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRoleTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole
            //instance = new EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRoleInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole
            //Assert.IsType<EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesRole>(instance);
        }


        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [Fact]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

    }

}
