/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest
        //private EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest instance;

        public EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequestTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest
            //instance = new EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest
            //Assert.IsType<EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsRequestsCreateApiResourceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
