/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel
        //private EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel instance;

        public EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModelTests()
        {
            // TODO uncomment below to create an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel
            //instance = new EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel
        /// </summary>
        [Fact]
        public void EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel
            //Assert.IsType<EdGraphHttpAggregatorsManagementApiControllersV1ViewModelsResponsesApiResourceResponsePaginatedItemsViewModel>(instance);
        }


        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
