/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiClientV1ClientListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiClientV1ClientListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiClientV1ClientListResponse
        //private IdentityApiClientV1ClientListResponse instance;

        public IdentityApiClientV1ClientListResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiClientV1ClientListResponse
            //instance = new IdentityApiClientV1ClientListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiClientV1ClientListResponse
        /// </summary>
        [Fact]
        public void IdentityApiClientV1ClientListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiClientV1ClientListResponse
            //Assert.IsType<IdentityApiClientV1ClientListResponse>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientName'
        /// </summary>
        [Fact]
        public void ClientNameTest()
        {
            // TODO unit test for the property 'ClientName'
        }
        /// <summary>
        /// Test the property 'ClientUri'
        /// </summary>
        [Fact]
        public void ClientUriTest()
        {
            // TODO unit test for the property 'ClientUri'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }
        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }

    }

}
