/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiClientV1AccessTokenType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiClientV1AccessTokenTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiClientV1AccessTokenType
        //private IdentityApiClientV1AccessTokenType instance;

        public IdentityApiClientV1AccessTokenTypeTests()
        {
            // TODO uncomment below to create an instance of IdentityApiClientV1AccessTokenType
            //instance = new IdentityApiClientV1AccessTokenType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiClientV1AccessTokenType
        /// </summary>
        [Fact]
        public void IdentityApiClientV1AccessTokenTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiClientV1AccessTokenType
            //Assert.IsType<IdentityApiClientV1AccessTokenType>(instance);
        }



    }

}
