/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Management.Client.Model;
using EdGraph.Management.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Management.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RegistrationApiRegistrationV1SubmittedBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistrationApiRegistrationV1SubmittedByTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegistrationApiRegistrationV1SubmittedBy
        //private RegistrationApiRegistrationV1SubmittedBy instance;

        public RegistrationApiRegistrationV1SubmittedByTests()
        {
            // TODO uncomment below to create an instance of RegistrationApiRegistrationV1SubmittedBy
            //instance = new RegistrationApiRegistrationV1SubmittedBy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegistrationApiRegistrationV1SubmittedBy
        /// </summary>
        [Fact]
        public void RegistrationApiRegistrationV1SubmittedByInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegistrationApiRegistrationV1SubmittedBy
            //Assert.IsType<RegistrationApiRegistrationV1SubmittedBy>(instance);
        }



    }

}
