/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Management.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Management.Client.Model
{
    /// <summary>
    /// Defines ApplicationApi.Application.V2.ApplicationType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ApplicationApiApplicationV2ApplicationType
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum SSO for value: SSO
        /// </summary>
        [EnumMember(Value = "SSO")]
        SSO = 2,

        /// <summary>
        /// Enum Link for value: Link
        /// </summary>
        [EnumMember(Value = "Link")]
        Link = 3

    }

}
