/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Management.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Management.Client.Model
{
    /// <summary>
    /// DataSyncApiProviderV1CreateConnectionTypeRequest
    /// </summary>
    [DataContract(Name = "DataSyncApi.Provider.V1.CreateConnectionTypeRequest")]
    public partial class DataSyncApiProviderV1CreateConnectionTypeRequest : IEquatable<DataSyncApiProviderV1CreateConnectionTypeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataSyncApiProviderV1CreateConnectionTypeRequest" /> class.
        /// </summary>
        /// <param name="providerId">providerId.</param>
        /// <param name="connectionTypeId">connectionTypeId.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="documentationUri">documentationUri.</param>
        public DataSyncApiProviderV1CreateConnectionTypeRequest(string providerId = default(string), string connectionTypeId = default(string), string name = default(string), string description = default(string), string documentationUri = default(string))
        {
            this.ProviderId = providerId;
            this.ConnectionTypeId = connectionTypeId;
            this.Name = name;
            this.Description = description;
            this.DocumentationUri = documentationUri;
        }

        /// <summary>
        /// Gets or Sets ProviderId
        /// </summary>
        [DataMember(Name = "providerId", EmitDefaultValue = true)]
        public string ProviderId { get; set; }

        /// <summary>
        /// Gets or Sets ConnectionTypeId
        /// </summary>
        [DataMember(Name = "connectionTypeId", EmitDefaultValue = true)]
        public string ConnectionTypeId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets DocumentationUri
        /// </summary>
        [DataMember(Name = "documentationUri", EmitDefaultValue = true)]
        public string DocumentationUri { get; set; }

        /// <summary>
        /// Gets or Sets ConnectionMetadataFields
        /// </summary>
        [DataMember(Name = "connectionMetadataFields", EmitDefaultValue = true)]
        public List<DataSyncApiProviderV1ConnectionMetadataField> ConnectionMetadataFields { get; private set; }

        /// <summary>
        /// Returns false as ConnectionMetadataFields should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeConnectionMetadataFields()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataSyncApiProviderV1CreateConnectionTypeRequest {\n");
            sb.Append("  ProviderId: ").Append(ProviderId).Append("\n");
            sb.Append("  ConnectionTypeId: ").Append(ConnectionTypeId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DocumentationUri: ").Append(DocumentationUri).Append("\n");
            sb.Append("  ConnectionMetadataFields: ").Append(ConnectionMetadataFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataSyncApiProviderV1CreateConnectionTypeRequest);
        }

        /// <summary>
        /// Returns true if DataSyncApiProviderV1CreateConnectionTypeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DataSyncApiProviderV1CreateConnectionTypeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataSyncApiProviderV1CreateConnectionTypeRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProviderId == input.ProviderId ||
                    (this.ProviderId != null &&
                    this.ProviderId.Equals(input.ProviderId))
                ) && 
                (
                    this.ConnectionTypeId == input.ConnectionTypeId ||
                    (this.ConnectionTypeId != null &&
                    this.ConnectionTypeId.Equals(input.ConnectionTypeId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DocumentationUri == input.DocumentationUri ||
                    (this.DocumentationUri != null &&
                    this.DocumentationUri.Equals(input.DocumentationUri))
                ) && 
                (
                    this.ConnectionMetadataFields == input.ConnectionMetadataFields ||
                    this.ConnectionMetadataFields != null &&
                    input.ConnectionMetadataFields != null &&
                    this.ConnectionMetadataFields.SequenceEqual(input.ConnectionMetadataFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProviderId != null)
                {
                    hashCode = (hashCode * 59) + this.ProviderId.GetHashCode();
                }
                if (this.ConnectionTypeId != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionTypeId.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.DocumentationUri != null)
                {
                    hashCode = (hashCode * 59) + this.DocumentationUri.GetHashCode();
                }
                if (this.ConnectionMetadataFields != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionMetadataFields.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
