/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Management.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Management.Client.Model
{
    /// <summary>
    /// DataSyncApiProviderV1ConnectionTypeCreatedResponse
    /// </summary>
    [DataContract(Name = "DataSyncApi.Provider.V1.ConnectionTypeCreatedResponse")]
    public partial class DataSyncApiProviderV1ConnectionTypeCreatedResponse : IEquatable<DataSyncApiProviderV1ConnectionTypeCreatedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataSyncApiProviderV1ConnectionTypeCreatedResponse" /> class.
        /// </summary>
        /// <param name="providerId">providerId.</param>
        /// <param name="connectionTypeId">connectionTypeId.</param>
        public DataSyncApiProviderV1ConnectionTypeCreatedResponse(string providerId = default(string), string connectionTypeId = default(string))
        {
            this.ProviderId = providerId;
            this.ConnectionTypeId = connectionTypeId;
        }

        /// <summary>
        /// Gets or Sets ProviderId
        /// </summary>
        [DataMember(Name = "providerId", EmitDefaultValue = true)]
        public string ProviderId { get; set; }

        /// <summary>
        /// Gets or Sets ConnectionTypeId
        /// </summary>
        [DataMember(Name = "connectionTypeId", EmitDefaultValue = true)]
        public string ConnectionTypeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataSyncApiProviderV1ConnectionTypeCreatedResponse {\n");
            sb.Append("  ProviderId: ").Append(ProviderId).Append("\n");
            sb.Append("  ConnectionTypeId: ").Append(ConnectionTypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataSyncApiProviderV1ConnectionTypeCreatedResponse);
        }

        /// <summary>
        /// Returns true if DataSyncApiProviderV1ConnectionTypeCreatedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DataSyncApiProviderV1ConnectionTypeCreatedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataSyncApiProviderV1ConnectionTypeCreatedResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProviderId == input.ProviderId ||
                    (this.ProviderId != null &&
                    this.ProviderId.Equals(input.ProviderId))
                ) && 
                (
                    this.ConnectionTypeId == input.ConnectionTypeId ||
                    (this.ConnectionTypeId != null &&
                    this.ConnectionTypeId.Equals(input.ConnectionTypeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProviderId != null)
                {
                    hashCode = (hashCode * 59) + this.ProviderId.GetHashCode();
                }
                if (this.ConnectionTypeId != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionTypeId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
