/*
 * Management Api
 *
 * Api to help platform wide items such as users, tenants, applications, subscriptions, etc.
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Management.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Management.Client.Model
{
    /// <summary>
    /// Defines IdentityApi.Client.V1.AccessTokenType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IdentityApiClientV1AccessTokenType
    {
        /// <summary>
        /// Enum Jwt for value: Jwt
        /// </summary>
        [EnumMember(Value = "Jwt")]
        Jwt = 1,

        /// <summary>
        /// Enum Reference for value: Reference
        /// </summary>
        [EnumMember(Value = "Reference")]
        Reference = 2

    }

}
